//! Base types and imports for FFI.
//!
//! This file is generated automatically.

#![allow(non_camel_case_types)]

/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _dftd3_error {
    _unused: [u8; 0],
}
#[doc = " Error handle class"]
pub type dftd3_error = *mut _dftd3_error;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _dftd3_structure {
    _unused: [u8; 0],
}
#[doc = " Molecular structure data class"]
pub type dftd3_structure = *mut _dftd3_structure;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _dftd3_model {
    _unused: [u8; 0],
}
#[doc = " Dispersion model class"]
pub type dftd3_model = *mut _dftd3_model;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _dftd3_gcp {
    _unused: [u8; 0],
}
#[doc = " Counter-poisecorrection parameters class"]
pub type dftd3_gcp = *mut _dftd3_gcp;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _dftd3_param {
    _unused: [u8; 0],
}
#[doc = " Damping parameter class"]
pub type dftd3_param = *mut _dftd3_param;
