name: test-dftd3-src

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run tests directly
        run: |
          cd dftd3-src
          export DFTD3_SRC_DEV=1
          cargo test --test "*" -vv --features="build_from_source static" -- --nocapture
  
  build-dynamic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run tests directly
        run: |
          cd dftd3-src
          cargo test --test "*" -vv --features="build_from_source" -- --nocapture
    
  external-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
      - name: run tests directly
        run: |
          cd dftd3-src
          conda install dftd3-python -c conda-forge
          ls /usr/share/miniconda/lib
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/share/miniconda/lib
          export DFTD3_SRC_DEV=1
          cargo test --test "*" -vv --features="static" -- --nocapture
  
  external-dynamic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
      - name: run tests directly
        run: |
          cd dftd3-src
          conda install dftd3-python -c conda-forge
          ls /usr/share/miniconda/lib
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/share/miniconda/lib
          cargo test --test "*" -vv -- --nocapture
